// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: evented/projector/projector.proto

package name.benjaminabbitt.evented.projector;

public final class ProjectorOuterClass {
  private ProjectorOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!evented/projector/projector.proto\022\021eve" +
      "nted.projector\032\032evented/core/evented.pro" +
      "to\032\033google/protobuf/empty.proto2\213\001\n\tProj" +
      "ector\022A\n\nHandleSync\022\027.evented.core.Event" +
      "Book\032\030.evented.core.Projection\"\000\022;\n\006Hand" +
      "le\022\027.evented.core.EventBook\032\026.google.pro" +
      "tobuf.Empty\"\000BD\n%name.benjaminabbitt.eve" +
      "nted.projectorZ\033projector;evented_projec" +
      "torb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          name.benjaminabbitt.evented.core.Evented.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    name.benjaminabbitt.evented.core.Evented.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
