// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: evented/query/query.proto

package name.benjaminabbitt.wwwwwh.where.url.projection.sample.core.query;

import name.benjaminabbitt.wwwwwh.where.url.projection.sample.core.Evented;

public final class QueryOuterClass {
  private QueryOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface QueryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:evented.query.Query)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string domain = 1;</code>
     * @return The domain.
     */
    java.lang.String getDomain();
    /**
     * <code>string domain = 1;</code>
     * @return The bytes for domain.
     */
    com.google.protobuf.ByteString
        getDomainBytes();

    /**
     * <code>.evented.core.UUID root = 2;</code>
     * @return Whether the root field is set.
     */
    boolean hasRoot();
    /**
     * <code>.evented.core.UUID root = 2;</code>
     * @return The root.
     */
    Evented.UUID getRoot();
    /**
     * <code>.evented.core.UUID root = 2;</code>
     */
    Evented.UUIDOrBuilder getRootOrBuilder();

    /**
     * <code>uint32 lowerBound = 3;</code>
     * @return The lowerBound.
     */
    int getLowerBound();

    /**
     * <code>uint32 upperBound = 4;</code>
     * @return The upperBound.
     */
    int getUpperBound();
  }
  /**
   * Protobuf type {@code evented.query.Query}
   */
  public  static final class Query extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:evented.query.Query)
      QueryOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Query.newBuilder() to construct.
    private Query(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Query() {
      domain_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Query();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Query(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              domain_ = s;
              break;
            }
            case 18: {
              Evented.UUID.Builder subBuilder = null;
              if (root_ != null) {
                subBuilder = root_.toBuilder();
              }
              root_ = input.readMessage(Evented.UUID.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(root_);
                root_ = subBuilder.buildPartial();
              }

              break;
            }
            case 24: {

              lowerBound_ = input.readUInt32();
              break;
            }
            case 32: {

              upperBound_ = input.readUInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return QueryOuterClass.internal_static_evented_query_Query_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return QueryOuterClass.internal_static_evented_query_Query_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              QueryOuterClass.Query.class, QueryOuterClass.Query.Builder.class);
    }

    public static final int DOMAIN_FIELD_NUMBER = 1;
    private volatile java.lang.Object domain_;
    /**
     * <code>string domain = 1;</code>
     * @return The domain.
     */
    public java.lang.String getDomain() {
      java.lang.Object ref = domain_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        domain_ = s;
        return s;
      }
    }
    /**
     * <code>string domain = 1;</code>
     * @return The bytes for domain.
     */
    public com.google.protobuf.ByteString
        getDomainBytes() {
      java.lang.Object ref = domain_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        domain_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ROOT_FIELD_NUMBER = 2;
    private Evented.UUID root_;
    /**
     * <code>.evented.core.UUID root = 2;</code>
     * @return Whether the root field is set.
     */
    public boolean hasRoot() {
      return root_ != null;
    }
    /**
     * <code>.evented.core.UUID root = 2;</code>
     * @return The root.
     */
    public Evented.UUID getRoot() {
      return root_ == null ? Evented.UUID.getDefaultInstance() : root_;
    }
    /**
     * <code>.evented.core.UUID root = 2;</code>
     */
    public Evented.UUIDOrBuilder getRootOrBuilder() {
      return getRoot();
    }

    public static final int LOWERBOUND_FIELD_NUMBER = 3;
    private int lowerBound_;
    /**
     * <code>uint32 lowerBound = 3;</code>
     * @return The lowerBound.
     */
    public int getLowerBound() {
      return lowerBound_;
    }

    public static final int UPPERBOUND_FIELD_NUMBER = 4;
    private int upperBound_;
    /**
     * <code>uint32 upperBound = 4;</code>
     * @return The upperBound.
     */
    public int getUpperBound() {
      return upperBound_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDomainBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, domain_);
      }
      if (root_ != null) {
        output.writeMessage(2, getRoot());
      }
      if (lowerBound_ != 0) {
        output.writeUInt32(3, lowerBound_);
      }
      if (upperBound_ != 0) {
        output.writeUInt32(4, upperBound_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDomainBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, domain_);
      }
      if (root_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getRoot());
      }
      if (lowerBound_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, lowerBound_);
      }
      if (upperBound_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, upperBound_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof QueryOuterClass.Query)) {
        return super.equals(obj);
      }
      QueryOuterClass.Query other = (QueryOuterClass.Query) obj;

      if (!getDomain()
          .equals(other.getDomain())) return false;
      if (hasRoot() != other.hasRoot()) return false;
      if (hasRoot()) {
        if (!getRoot()
            .equals(other.getRoot())) return false;
      }
      if (getLowerBound()
          != other.getLowerBound()) return false;
      if (getUpperBound()
          != other.getUpperBound()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DOMAIN_FIELD_NUMBER;
      hash = (53 * hash) + getDomain().hashCode();
      if (hasRoot()) {
        hash = (37 * hash) + ROOT_FIELD_NUMBER;
        hash = (53 * hash) + getRoot().hashCode();
      }
      hash = (37 * hash) + LOWERBOUND_FIELD_NUMBER;
      hash = (53 * hash) + getLowerBound();
      hash = (37 * hash) + UPPERBOUND_FIELD_NUMBER;
      hash = (53 * hash) + getUpperBound();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static QueryOuterClass.Query parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static QueryOuterClass.Query parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static QueryOuterClass.Query parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static QueryOuterClass.Query parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static QueryOuterClass.Query parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static QueryOuterClass.Query parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static QueryOuterClass.Query parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static QueryOuterClass.Query parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static QueryOuterClass.Query parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static QueryOuterClass.Query parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static QueryOuterClass.Query parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static QueryOuterClass.Query parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(QueryOuterClass.Query prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code evented.query.Query}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:evented.query.Query)
        QueryOuterClass.QueryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return QueryOuterClass.internal_static_evented_query_Query_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return QueryOuterClass.internal_static_evented_query_Query_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                QueryOuterClass.Query.class, QueryOuterClass.Query.Builder.class);
      }

      // Construct using name.benjaminabbitt.evented.core.query.QueryOuterClass.Query.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        domain_ = "";

        if (rootBuilder_ == null) {
          root_ = null;
        } else {
          root_ = null;
          rootBuilder_ = null;
        }
        lowerBound_ = 0;

        upperBound_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return QueryOuterClass.internal_static_evented_query_Query_descriptor;
      }

      @java.lang.Override
      public QueryOuterClass.Query getDefaultInstanceForType() {
        return QueryOuterClass.Query.getDefaultInstance();
      }

      @java.lang.Override
      public QueryOuterClass.Query build() {
        QueryOuterClass.Query result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public QueryOuterClass.Query buildPartial() {
        QueryOuterClass.Query result = new QueryOuterClass.Query(this);
        result.domain_ = domain_;
        if (rootBuilder_ == null) {
          result.root_ = root_;
        } else {
          result.root_ = rootBuilder_.build();
        }
        result.lowerBound_ = lowerBound_;
        result.upperBound_ = upperBound_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof QueryOuterClass.Query) {
          return mergeFrom((QueryOuterClass.Query)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(QueryOuterClass.Query other) {
        if (other == QueryOuterClass.Query.getDefaultInstance()) return this;
        if (!other.getDomain().isEmpty()) {
          domain_ = other.domain_;
          onChanged();
        }
        if (other.hasRoot()) {
          mergeRoot(other.getRoot());
        }
        if (other.getLowerBound() != 0) {
          setLowerBound(other.getLowerBound());
        }
        if (other.getUpperBound() != 0) {
          setUpperBound(other.getUpperBound());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        QueryOuterClass.Query parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (QueryOuterClass.Query) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object domain_ = "";
      /**
       * <code>string domain = 1;</code>
       * @return The domain.
       */
      public java.lang.String getDomain() {
        java.lang.Object ref = domain_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          domain_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string domain = 1;</code>
       * @return The bytes for domain.
       */
      public com.google.protobuf.ByteString
          getDomainBytes() {
        java.lang.Object ref = domain_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          domain_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string domain = 1;</code>
       * @param value The domain to set.
       * @return This builder for chaining.
       */
      public Builder setDomain(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        domain_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string domain = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDomain() {
        
        domain_ = getDefaultInstance().getDomain();
        onChanged();
        return this;
      }
      /**
       * <code>string domain = 1;</code>
       * @param value The bytes for domain to set.
       * @return This builder for chaining.
       */
      public Builder setDomainBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        domain_ = value;
        onChanged();
        return this;
      }

      private Evented.UUID root_;
      private com.google.protobuf.SingleFieldBuilderV3<
          Evented.UUID, Evented.UUID.Builder, Evented.UUIDOrBuilder> rootBuilder_;
      /**
       * <code>.evented.core.UUID root = 2;</code>
       * @return Whether the root field is set.
       */
      public boolean hasRoot() {
        return rootBuilder_ != null || root_ != null;
      }
      /**
       * <code>.evented.core.UUID root = 2;</code>
       * @return The root.
       */
      public Evented.UUID getRoot() {
        if (rootBuilder_ == null) {
          return root_ == null ? Evented.UUID.getDefaultInstance() : root_;
        } else {
          return rootBuilder_.getMessage();
        }
      }
      /**
       * <code>.evented.core.UUID root = 2;</code>
       */
      public Builder setRoot(Evented.UUID value) {
        if (rootBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          root_ = value;
          onChanged();
        } else {
          rootBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.evented.core.UUID root = 2;</code>
       */
      public Builder setRoot(
          Evented.UUID.Builder builderForValue) {
        if (rootBuilder_ == null) {
          root_ = builderForValue.build();
          onChanged();
        } else {
          rootBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.evented.core.UUID root = 2;</code>
       */
      public Builder mergeRoot(Evented.UUID value) {
        if (rootBuilder_ == null) {
          if (root_ != null) {
            root_ =
              Evented.UUID.newBuilder(root_).mergeFrom(value).buildPartial();
          } else {
            root_ = value;
          }
          onChanged();
        } else {
          rootBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.evented.core.UUID root = 2;</code>
       */
      public Builder clearRoot() {
        if (rootBuilder_ == null) {
          root_ = null;
          onChanged();
        } else {
          root_ = null;
          rootBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.evented.core.UUID root = 2;</code>
       */
      public Evented.UUID.Builder getRootBuilder() {
        
        onChanged();
        return getRootFieldBuilder().getBuilder();
      }
      /**
       * <code>.evented.core.UUID root = 2;</code>
       */
      public Evented.UUIDOrBuilder getRootOrBuilder() {
        if (rootBuilder_ != null) {
          return rootBuilder_.getMessageOrBuilder();
        } else {
          return root_ == null ?
              Evented.UUID.getDefaultInstance() : root_;
        }
      }
      /**
       * <code>.evented.core.UUID root = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Evented.UUID, Evented.UUID.Builder, Evented.UUIDOrBuilder>
          getRootFieldBuilder() {
        if (rootBuilder_ == null) {
          rootBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Evented.UUID, Evented.UUID.Builder, Evented.UUIDOrBuilder>(
                  getRoot(),
                  getParentForChildren(),
                  isClean());
          root_ = null;
        }
        return rootBuilder_;
      }

      private int lowerBound_ ;
      /**
       * <code>uint32 lowerBound = 3;</code>
       * @return The lowerBound.
       */
      public int getLowerBound() {
        return lowerBound_;
      }
      /**
       * <code>uint32 lowerBound = 3;</code>
       * @param value The lowerBound to set.
       * @return This builder for chaining.
       */
      public Builder setLowerBound(int value) {
        
        lowerBound_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 lowerBound = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLowerBound() {
        
        lowerBound_ = 0;
        onChanged();
        return this;
      }

      private int upperBound_ ;
      /**
       * <code>uint32 upperBound = 4;</code>
       * @return The upperBound.
       */
      public int getUpperBound() {
        return upperBound_;
      }
      /**
       * <code>uint32 upperBound = 4;</code>
       * @param value The upperBound to set.
       * @return This builder for chaining.
       */
      public Builder setUpperBound(int value) {
        
        upperBound_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 upperBound = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearUpperBound() {
        
        upperBound_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:evented.query.Query)
    }

    // @@protoc_insertion_point(class_scope:evented.query.Query)
    private static final QueryOuterClass.Query DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new QueryOuterClass.Query();
    }

    public static QueryOuterClass.Query getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Query>
        PARSER = new com.google.protobuf.AbstractParser<Query>() {
      @java.lang.Override
      public Query parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Query(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Query> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Query> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public QueryOuterClass.Query getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AggregateRootOrBuilder extends
      // @@protoc_insertion_point(interface_extends:evented.query.AggregateRoot)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string domain = 1;</code>
     * @return The domain.
     */
    java.lang.String getDomain();
    /**
     * <code>string domain = 1;</code>
     * @return The bytes for domain.
     */
    com.google.protobuf.ByteString
        getDomainBytes();

    /**
     * <code>.evented.core.UUID root = 2;</code>
     * @return Whether the root field is set.
     */
    boolean hasRoot();
    /**
     * <code>.evented.core.UUID root = 2;</code>
     * @return The root.
     */
    Evented.UUID getRoot();
    /**
     * <code>.evented.core.UUID root = 2;</code>
     */
    Evented.UUIDOrBuilder getRootOrBuilder();
  }
  /**
   * Protobuf type {@code evented.query.AggregateRoot}
   */
  public  static final class AggregateRoot extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:evented.query.AggregateRoot)
      AggregateRootOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AggregateRoot.newBuilder() to construct.
    private AggregateRoot(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AggregateRoot() {
      domain_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AggregateRoot();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AggregateRoot(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              domain_ = s;
              break;
            }
            case 18: {
              Evented.UUID.Builder subBuilder = null;
              if (root_ != null) {
                subBuilder = root_.toBuilder();
              }
              root_ = input.readMessage(Evented.UUID.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(root_);
                root_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return QueryOuterClass.internal_static_evented_query_AggregateRoot_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return QueryOuterClass.internal_static_evented_query_AggregateRoot_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              QueryOuterClass.AggregateRoot.class, QueryOuterClass.AggregateRoot.Builder.class);
    }

    public static final int DOMAIN_FIELD_NUMBER = 1;
    private volatile java.lang.Object domain_;
    /**
     * <code>string domain = 1;</code>
     * @return The domain.
     */
    public java.lang.String getDomain() {
      java.lang.Object ref = domain_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        domain_ = s;
        return s;
      }
    }
    /**
     * <code>string domain = 1;</code>
     * @return The bytes for domain.
     */
    public com.google.protobuf.ByteString
        getDomainBytes() {
      java.lang.Object ref = domain_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        domain_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ROOT_FIELD_NUMBER = 2;
    private Evented.UUID root_;
    /**
     * <code>.evented.core.UUID root = 2;</code>
     * @return Whether the root field is set.
     */
    public boolean hasRoot() {
      return root_ != null;
    }
    /**
     * <code>.evented.core.UUID root = 2;</code>
     * @return The root.
     */
    public Evented.UUID getRoot() {
      return root_ == null ? Evented.UUID.getDefaultInstance() : root_;
    }
    /**
     * <code>.evented.core.UUID root = 2;</code>
     */
    public Evented.UUIDOrBuilder getRootOrBuilder() {
      return getRoot();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDomainBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, domain_);
      }
      if (root_ != null) {
        output.writeMessage(2, getRoot());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDomainBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, domain_);
      }
      if (root_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getRoot());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof QueryOuterClass.AggregateRoot)) {
        return super.equals(obj);
      }
      QueryOuterClass.AggregateRoot other = (QueryOuterClass.AggregateRoot) obj;

      if (!getDomain()
          .equals(other.getDomain())) return false;
      if (hasRoot() != other.hasRoot()) return false;
      if (hasRoot()) {
        if (!getRoot()
            .equals(other.getRoot())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DOMAIN_FIELD_NUMBER;
      hash = (53 * hash) + getDomain().hashCode();
      if (hasRoot()) {
        hash = (37 * hash) + ROOT_FIELD_NUMBER;
        hash = (53 * hash) + getRoot().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static QueryOuterClass.AggregateRoot parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static QueryOuterClass.AggregateRoot parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static QueryOuterClass.AggregateRoot parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static QueryOuterClass.AggregateRoot parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static QueryOuterClass.AggregateRoot parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static QueryOuterClass.AggregateRoot parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static QueryOuterClass.AggregateRoot parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static QueryOuterClass.AggregateRoot parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static QueryOuterClass.AggregateRoot parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static QueryOuterClass.AggregateRoot parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static QueryOuterClass.AggregateRoot parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static QueryOuterClass.AggregateRoot parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(QueryOuterClass.AggregateRoot prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code evented.query.AggregateRoot}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:evented.query.AggregateRoot)
        QueryOuterClass.AggregateRootOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return QueryOuterClass.internal_static_evented_query_AggregateRoot_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return QueryOuterClass.internal_static_evented_query_AggregateRoot_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                QueryOuterClass.AggregateRoot.class, QueryOuterClass.AggregateRoot.Builder.class);
      }

      // Construct using name.benjaminabbitt.evented.core.query.QueryOuterClass.AggregateRoot.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        domain_ = "";

        if (rootBuilder_ == null) {
          root_ = null;
        } else {
          root_ = null;
          rootBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return QueryOuterClass.internal_static_evented_query_AggregateRoot_descriptor;
      }

      @java.lang.Override
      public QueryOuterClass.AggregateRoot getDefaultInstanceForType() {
        return QueryOuterClass.AggregateRoot.getDefaultInstance();
      }

      @java.lang.Override
      public QueryOuterClass.AggregateRoot build() {
        QueryOuterClass.AggregateRoot result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public QueryOuterClass.AggregateRoot buildPartial() {
        QueryOuterClass.AggregateRoot result = new QueryOuterClass.AggregateRoot(this);
        result.domain_ = domain_;
        if (rootBuilder_ == null) {
          result.root_ = root_;
        } else {
          result.root_ = rootBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof QueryOuterClass.AggregateRoot) {
          return mergeFrom((QueryOuterClass.AggregateRoot)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(QueryOuterClass.AggregateRoot other) {
        if (other == QueryOuterClass.AggregateRoot.getDefaultInstance()) return this;
        if (!other.getDomain().isEmpty()) {
          domain_ = other.domain_;
          onChanged();
        }
        if (other.hasRoot()) {
          mergeRoot(other.getRoot());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        QueryOuterClass.AggregateRoot parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (QueryOuterClass.AggregateRoot) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object domain_ = "";
      /**
       * <code>string domain = 1;</code>
       * @return The domain.
       */
      public java.lang.String getDomain() {
        java.lang.Object ref = domain_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          domain_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string domain = 1;</code>
       * @return The bytes for domain.
       */
      public com.google.protobuf.ByteString
          getDomainBytes() {
        java.lang.Object ref = domain_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          domain_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string domain = 1;</code>
       * @param value The domain to set.
       * @return This builder for chaining.
       */
      public Builder setDomain(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        domain_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string domain = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDomain() {
        
        domain_ = getDefaultInstance().getDomain();
        onChanged();
        return this;
      }
      /**
       * <code>string domain = 1;</code>
       * @param value The bytes for domain to set.
       * @return This builder for chaining.
       */
      public Builder setDomainBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        domain_ = value;
        onChanged();
        return this;
      }

      private Evented.UUID root_;
      private com.google.protobuf.SingleFieldBuilderV3<
          Evented.UUID, Evented.UUID.Builder, Evented.UUIDOrBuilder> rootBuilder_;
      /**
       * <code>.evented.core.UUID root = 2;</code>
       * @return Whether the root field is set.
       */
      public boolean hasRoot() {
        return rootBuilder_ != null || root_ != null;
      }
      /**
       * <code>.evented.core.UUID root = 2;</code>
       * @return The root.
       */
      public Evented.UUID getRoot() {
        if (rootBuilder_ == null) {
          return root_ == null ? Evented.UUID.getDefaultInstance() : root_;
        } else {
          return rootBuilder_.getMessage();
        }
      }
      /**
       * <code>.evented.core.UUID root = 2;</code>
       */
      public Builder setRoot(Evented.UUID value) {
        if (rootBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          root_ = value;
          onChanged();
        } else {
          rootBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.evented.core.UUID root = 2;</code>
       */
      public Builder setRoot(
          Evented.UUID.Builder builderForValue) {
        if (rootBuilder_ == null) {
          root_ = builderForValue.build();
          onChanged();
        } else {
          rootBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.evented.core.UUID root = 2;</code>
       */
      public Builder mergeRoot(Evented.UUID value) {
        if (rootBuilder_ == null) {
          if (root_ != null) {
            root_ =
              Evented.UUID.newBuilder(root_).mergeFrom(value).buildPartial();
          } else {
            root_ = value;
          }
          onChanged();
        } else {
          rootBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.evented.core.UUID root = 2;</code>
       */
      public Builder clearRoot() {
        if (rootBuilder_ == null) {
          root_ = null;
          onChanged();
        } else {
          root_ = null;
          rootBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.evented.core.UUID root = 2;</code>
       */
      public Evented.UUID.Builder getRootBuilder() {
        
        onChanged();
        return getRootFieldBuilder().getBuilder();
      }
      /**
       * <code>.evented.core.UUID root = 2;</code>
       */
      public Evented.UUIDOrBuilder getRootOrBuilder() {
        if (rootBuilder_ != null) {
          return rootBuilder_.getMessageOrBuilder();
        } else {
          return root_ == null ?
              Evented.UUID.getDefaultInstance() : root_;
        }
      }
      /**
       * <code>.evented.core.UUID root = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Evented.UUID, Evented.UUID.Builder, Evented.UUIDOrBuilder>
          getRootFieldBuilder() {
        if (rootBuilder_ == null) {
          rootBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Evented.UUID, Evented.UUID.Builder, Evented.UUIDOrBuilder>(
                  getRoot(),
                  getParentForChildren(),
                  isClean());
          root_ = null;
        }
        return rootBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:evented.query.AggregateRoot)
    }

    // @@protoc_insertion_point(class_scope:evented.query.AggregateRoot)
    private static final QueryOuterClass.AggregateRoot DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new QueryOuterClass.AggregateRoot();
    }

    public static QueryOuterClass.AggregateRoot getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AggregateRoot>
        PARSER = new com.google.protobuf.AbstractParser<AggregateRoot>() {
      @java.lang.Override
      public AggregateRoot parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AggregateRoot(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AggregateRoot> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AggregateRoot> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public QueryOuterClass.AggregateRoot getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TestByteArrayOrBuilder extends
      // @@protoc_insertion_point(interface_extends:evented.query.TestByteArray)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes bytes = 1;</code>
     * @return The bytes.
     */
    com.google.protobuf.ByteString getBytes();
  }
  /**
   * Protobuf type {@code evented.query.TestByteArray}
   */
  public  static final class TestByteArray extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:evented.query.TestByteArray)
      TestByteArrayOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TestByteArray.newBuilder() to construct.
    private TestByteArray(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TestByteArray() {
      bytes_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TestByteArray();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TestByteArray(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {

              bytes_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return QueryOuterClass.internal_static_evented_query_TestByteArray_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return QueryOuterClass.internal_static_evented_query_TestByteArray_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              QueryOuterClass.TestByteArray.class, QueryOuterClass.TestByteArray.Builder.class);
    }

    public static final int BYTES_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString bytes_;
    /**
     * <code>bytes bytes = 1;</code>
     * @return The bytes.
     */
    public com.google.protobuf.ByteString getBytes() {
      return bytes_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!bytes_.isEmpty()) {
        output.writeBytes(1, bytes_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!bytes_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, bytes_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof QueryOuterClass.TestByteArray)) {
        return super.equals(obj);
      }
      QueryOuterClass.TestByteArray other = (QueryOuterClass.TestByteArray) obj;

      if (!getBytes()
          .equals(other.getBytes())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BYTES_FIELD_NUMBER;
      hash = (53 * hash) + getBytes().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static QueryOuterClass.TestByteArray parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static QueryOuterClass.TestByteArray parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static QueryOuterClass.TestByteArray parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static QueryOuterClass.TestByteArray parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static QueryOuterClass.TestByteArray parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static QueryOuterClass.TestByteArray parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static QueryOuterClass.TestByteArray parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static QueryOuterClass.TestByteArray parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static QueryOuterClass.TestByteArray parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static QueryOuterClass.TestByteArray parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static QueryOuterClass.TestByteArray parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static QueryOuterClass.TestByteArray parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(QueryOuterClass.TestByteArray prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code evented.query.TestByteArray}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:evented.query.TestByteArray)
        QueryOuterClass.TestByteArrayOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return QueryOuterClass.internal_static_evented_query_TestByteArray_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return QueryOuterClass.internal_static_evented_query_TestByteArray_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                QueryOuterClass.TestByteArray.class, QueryOuterClass.TestByteArray.Builder.class);
      }

      // Construct using name.benjaminabbitt.evented.core.query.QueryOuterClass.TestByteArray.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bytes_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return QueryOuterClass.internal_static_evented_query_TestByteArray_descriptor;
      }

      @java.lang.Override
      public QueryOuterClass.TestByteArray getDefaultInstanceForType() {
        return QueryOuterClass.TestByteArray.getDefaultInstance();
      }

      @java.lang.Override
      public QueryOuterClass.TestByteArray build() {
        QueryOuterClass.TestByteArray result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public QueryOuterClass.TestByteArray buildPartial() {
        QueryOuterClass.TestByteArray result = new QueryOuterClass.TestByteArray(this);
        result.bytes_ = bytes_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof QueryOuterClass.TestByteArray) {
          return mergeFrom((QueryOuterClass.TestByteArray)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(QueryOuterClass.TestByteArray other) {
        if (other == QueryOuterClass.TestByteArray.getDefaultInstance()) return this;
        if (other.getBytes() != com.google.protobuf.ByteString.EMPTY) {
          setBytes(other.getBytes());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        QueryOuterClass.TestByteArray parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (QueryOuterClass.TestByteArray) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString bytes_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes bytes = 1;</code>
       * @return The bytes.
       */
      public com.google.protobuf.ByteString getBytes() {
        return bytes_;
      }
      /**
       * <code>bytes bytes = 1;</code>
       * @param value The bytes to set.
       * @return This builder for chaining.
       */
      public Builder setBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        bytes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes bytes = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearBytes() {
        
        bytes_ = getDefaultInstance().getBytes();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:evented.query.TestByteArray)
    }

    // @@protoc_insertion_point(class_scope:evented.query.TestByteArray)
    private static final QueryOuterClass.TestByteArray DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new QueryOuterClass.TestByteArray();
    }

    public static QueryOuterClass.TestByteArray getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TestByteArray>
        PARSER = new com.google.protobuf.AbstractParser<TestByteArray>() {
      @java.lang.Override
      public TestByteArray parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TestByteArray(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TestByteArray> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TestByteArray> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public QueryOuterClass.TestByteArray getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_evented_query_Query_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_evented_query_Query_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_evented_query_AggregateRoot_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_evented_query_AggregateRoot_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_evented_query_TestByteArray_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_evented_query_TestByteArray_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031evented/query/query.proto\022\revented.que" +
      "ry\032\032evented/core/evented.proto\032\033google/p" +
      "rotobuf/empty.proto\"a\n\005Query\022\016\n\006domain\030\001" +
      " \001(\t\022 \n\004root\030\002 \001(\0132\022.evented.core.UUID\022\022" +
      "\n\nlowerBound\030\003 \001(\r\022\022\n\nupperBound\030\004 \001(\r\"A" +
      "\n\rAggregateRoot\022\016\n\006domain\030\001 \001(\t\022 \n\004root\030" +
      "\002 \001(\0132\022.evented.core.UUID\"\036\n\rTestByteArr" +
      "ay\022\r\n\005bytes\030\001 \001(\0142\337\001\n\nEventQuery\022>\n\tGetE" +
      "vents\022\024.evented.query.Query\032\027.evented.co" +
      "re.EventBook\"\0000\001\022B\n\013Synchronize\022\024.evente" +
      "d.query.Query\032\027.evented.core.EventBook\"\000" +
      "(\0010\001\022M\n\021GetAggregateRoots\022\026.google.proto" +
      "buf.Empty\032\034.evented.query.AggregateRoot\"" +
      "\0000\001B=\n&name.benjaminabbitt.evented.core." +
      "queryZ\023query;evented_queryb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          Evented.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_evented_query_Query_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_evented_query_Query_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_evented_query_Query_descriptor,
        new java.lang.String[] { "Domain", "Root", "LowerBound", "UpperBound", });
    internal_static_evented_query_AggregateRoot_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_evented_query_AggregateRoot_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_evented_query_AggregateRoot_descriptor,
        new java.lang.String[] { "Domain", "Root", });
    internal_static_evented_query_TestByteArray_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_evented_query_TestByteArray_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_evented_query_TestByteArray_descriptor,
        new java.lang.String[] { "Bytes", });
    Evented.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
