grpc:
  server:
    port: 1748
    keep-alive-time: 3h
    max-inbound-message-size: 1024

micronaut:
  security:
    endpoints:
      login:
        enabled: true
      oauth:
        enabled: true
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_SECRET}
  application:
    name: ${APP_NAME}

tracing:
  jaeger:
    enabled: true
    sampler:
      probability: 1.0

consul:
  client:
    registration:
      enabled: true
    default-zone: ${CONSUL_HOST:localhost}:${CONSUL_PORT:80}

