grpc:
  server:
    port: 8081
    keep-alive-time: 3h
    max-inbound-message-size: 1024

micronaut:
  security:
    endpoints:
      login:
        enabled: true
      oauth:
        enabled: true
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: 'FIXME'
tracing:
  jaeger:
    enabled: true
    sampler:
      probability: 1.0