micronaut:
  security:
    endpoints:
      login:
        enabled: true
      oauth:
        enabled: true
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
tracing:
  jaeger:
    enabled: true
    sampler:
      probability: 0.1
mongodb.uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}
