// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: evented/projectorCoordinator/projectorCoordinator.proto

package name.benjaminabbitt.evented.projector.coordinator;

public final class ProjectorCoordinatorOuterClass {
  private ProjectorCoordinatorOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n7evented/projectorCoordinator/projector" +
      "Coordinator.proto\022\035evented.projector.coo" +
      "rdinator\032\032evented/core/evented.proto\032\033go" +
      "ogle/protobuf/empty.proto2\226\001\n\024ProjectorC" +
      "oordinator\022A\n\nHandleSync\022\027.evented.core." +
      "EventBook\032\030.evented.core.Projection\"\000\022;\n" +
      "\006Handle\022\027.evented.core.EventBook\032\026.googl" +
      "e.protobuf.Empty\"\000Bg\n1name.benjaminabbit" +
      "t.evented.projector.coordinatorZ2project" +
      "orCoordinator;evented_projector_coordina" +
      "torb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          name.benjaminabbitt.evented.core.Evented.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    name.benjaminabbitt.evented.core.Evented.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
