// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: evented/saga/saga.proto

package name.benjaminabbitt.evented.saga;

public final class SagaOuterClass {
  private SagaOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027evented/saga/saga.proto\022\014evented.saga\032" +
      "\032evented/core/evented.proto2\206\001\n\004Saga\022@\n\n" +
      "HandleSync\022\027.evented.core.EventBook\032\027.ev" +
      "ented.core.EventBook\"\000\022<\n\006Handle\022\027.event" +
      "ed.core.EventBook\032\027.evented.core.EventBo" +
      "ok\"\000B5\n name.benjaminabbitt.evented.saga" +
      "Z\021saga;evented_sagab\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          name.benjaminabbitt.evented.core.Evented.getDescriptor(),
        });
    name.benjaminabbitt.evented.core.Evented.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
